### ISSUE TITLE
Motor drivers

### ISSUE THREAD

**Issue by hargoniX** [ApoapsisHGV/CainSat#6]
Implement a driver for the DRV8838 motordriver, maybe PR this into dethoter/stepper-driver so we can use their a4988 driver as well which is required for ground control

**Comment by fxedel** [comment]
See the work at [ApoapsisHGV/DRV8838](https://github.com/ApoapsisHGV/DRV8838). I'd be very pleased if you could have a look at the examples and the rust structure, @hargoniX!
